dymensionxyz/dymension-rdk

app/logger.go
app/logger_test.go
cmd/rollappd/start.go

* supporting nested `With` calls
* flagModuleLogLevelOverride doesn't create new Logger instance
* Added tests
Using multiple instances of log isn't good practice (as logger have internal locks and shared resource mgmt)

feat: adding logger test and refactor

---

Makefile

Currently we override the expected chain-id format from `XXXX_000-00` to `XXXX_0000_00`
This PR removes this override, and the expected chain-id for a rollapp is the standard convention `XXXX_000-00`
---
For Author:
---
For Reviewer:
---

chore: remove the override of the expected chain id in EVM module

---

go.mod
go.sum
x/dist/keeper/allocation_test.go
x/dist/module.go
x/staking/keeper/keeper.go
x/staking/module.go

RDK's `staking` module overwrites original's `ApplyAndReturnValidatorSetUpdates` method.
this method called by `genutil` on genesis and returns the validators over ABCI
as we set the validators on the `sequencers` module, we override this method to **not** return the validators set
---
For Author:
---
For Reviewer:
---

feat: support stakers on genesis

---

docs/static/openapi.yml

Fixed few typo in the openapi.yml file from the docs. Those are minor changes. Have a nice evening.

chore(docs/static/openapi.yml): typo fix

---

server/commands.go

This PR replaces tendermint reset-state command by a local command that enables removing only state. Tendermint command tries to remove db files with different names.
Closes #287 
---
For Author:
---
For Reviewer:
---

fix: dymint reset-state command not working

---

x/mint/keeper/hooks_test.go
x/mint/keeper/mint_test.go
x/mint/types/params.go

chores: change mint_epoch_identifier to hour

---

go.sum
testutil/app/app.go

---
Closes #XXX
For Author:
---
For Reviewer:
---

fix(tests): update ibcKeeper use SequencersKeeper instead of stakingKeeper

---

server/commands.go

---
Closes #482 
For Author:
---
For Reviewer:
---

feat(rollapp): Add pruning command

---

server/config/config.go

Default to no pruning
With default values when pruning is enabled set to keep 10k blocks, prune states older then 100 at an interval of 10 states
---
Closes #XXX
For Author:
---
For Reviewer:
---

feat(server): add helper to set default pruning settings on the rdk level

---

server/consensus/handler.go
server/consensus/handler_test.go

ADR link https://www.notion.so/dymension/ADR-x-Sequencer-Messages-34f95e2b579e458e8bb4252da19324bd
Closes https://github.com/dymensionxyz/epics/issues/1
----
I have...
SDK Checklist
----
For Reviewer:
----

feat: consensus messages

---

x/gasless/keeper/fee_helper.go
x/gasless/keeper/fee_helper_test.go
x/gasless/keeper/gasless.go
x/gasless/keeper/gasless_test.go
x/gasless/keeper/genesis.go
x/gasless/keeper/grpc_query.go
x/gasless/keeper/keeper.go
x/gasless/keeper/store.go
x/gasless/keeper/usage_identifiers.go
x/gasless/types/keys.go

----
Closes #603 
I have...
SDK Checklist
----
For Reviewer:
----

fix(gasless): usage identifier validation and mapping to gas tank IDs

---

x/hub-genesis/keeper/keeper.go
x/hub-genesis/keeper/msg_server.go

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

feat: add channel 0 check for tokenless

---

x/tokenfactory/keeper/createdenom.go
x/tokenfactory/keeper/createdenom_test.go

when creating a token in tokenFactory, it creates by default a non valid metadata in the `x/bank`

fix(tokenfactory):  sets missing fields in the denommetadata

---

x/timeupgrade/types/msgs.go

`MsgSoftwareUpgrade` doesn't validate the time field in `ValidateBasic`
which will fail the execution after the proposal will pass

fix(timeupgrade): validating time in software upgrade proposal

---

go.mod
go.sum

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

fix(deps): bump dymint v.1.3.0-rc04

---

x/gasless/spec/02_state.md

**Fix Typo in `02_state.md`**
This PR corrects a typo in the `02_state.md` file. The word `consumtion` has been fixed to `consumption` for accuracy and consistency in the documentation.
- Corrected `consumtion` to `consumption` in the `02_state.md` file.
Fixing this typo helps maintain clear and precise documentation, which is essential for the project's understanding and use.
Please confirm the following before submitting:
- This PR only addresses a typo fix and does not introduce any other changes to the content.

fix typo in 02_state.md

---

x/tokenfactory/README.md

Corrected "Saftey" to "Safety" under the State Modifications section.

Typo fix README.md

---

testutil/app/app.go

Corrected "tranfer" to "transfer" in app.go.

chore: fix typo in app.go

---

.golangci.yml

----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

chore: fix golang ci lint config

---

x/gasless/keeper/gasless_test.go

Since Go 1.21, the functions in x/exp used here can already be replaced by functions from the standard library.
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----

refactor: replace golang.org/x/exp with stdlib
