dymensionxyz/dymension-rdk

- scripts/set_genesis_config.sh
- x/sequencers/types/genesis.go
> fixed script to use operator account address

- Makefile
- app/app.go
- app/app_evm.go
- go.mod
- go.sum
- scripts/set_genesis_config.sh
- testutil/utils/keys.go
- testutil/utils/test_app.go
- x/sequencers/genesis.go
- x/sequencers/genesis_test.go
- x/sequencers/keeper/keeper.go
- x/sequencers/keeper/msg_createSequencer.go
- x/sequencers/keeper/validator.go
- x/sequencers/module.go
- x/sequencers/testutils/testutils.go
- x/sequencers/types/errors.go
- x/sequencers/types/keys.go
- x/sequencers/types/types.go
In this PR, the app expects dymint to send a sequencer list through `RequestInitChain`
The sequencer stored on `Sequencer module`.
> feat: support getting active sequencers from dymint

- .github/workflows/test.yml
---
For Author:
---
For Reviewer:
--- 
> fix: ci lint failure 

- go.mod
- go.sum
---
For Author:
---
For Reviewer:
--- 
> build(deps): bumped dymint to v0.4.0-beta

- scripts/init_rollapp.sh
- scripts/set_genesis_config.sh
---
For Author:
---
For Reviewer:
--- 
> chore: doubled the default unbonding time

- x/sequencers/types/genesis.go
- x/sequencers/types/genesis_test.go
---
For Author:
---
For Reviewer:
--- 
> chore: validates there are sequencers on genesis

- scripts/init_rollapp.sh
- scripts/set_genesis_config.sh
---
For Author:
---
For Reviewer:
--- 
> fix: fixed bug when modifying staking params in init script

- scripts/shared.sh
Changed `dymint` config so it will calculate the fee instead of using fixed fee.
The gas price is set in the env variables and will be used by the upcoming CLI tool. 
---
For Author:
---
For Reviewer:
--- 
> chore: using gas_prices instead of fixed fee for batch submit to the hub

- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---
> fix: changed the ibc_go replace directive to the release/v5.1.x_dymint branch

- scripts/init_rollapp.sh
custom strategy of:
2 weeks of states kept
pruning in interval of 10 minutes
---
For Author:
---
For Reviewer:
---
> chore: Set default pruning of the rollapp to be custom

- cmd/common/dymint_config.go
- cmd/evm/root.go
- cmd/evm/start.go
- cmd/rollappd/cmd/root.go
- cmd/rollappd/cmd/start.go
- go.mod
- go.sum
- scripts/run_rollapp.sh
- scripts/shared.sh
---
For Author:
---
For Reviewer:
---
> feat: support reading dymint configuration from file

- README.md
---
For Author:
---
For Reviewer:
---
> docs: fix invalid flag name

- cmd/evm/start.go
- cmd/rollappd/cmd/start.go
- go.mod
- go.sum
Draft state until https://github.com/dymensionxyz/dymint/pull/331 merged.
Will fix the dymint reference afterwards 
---
For Author:
---
For Reviewer:
---
> fix: fixed overwritten signal handler in `cmd/start`

- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---
> build(deps): Bumped dymint to v0.5.0-rc1.

- x/mint/keeper/keeper.go
---
For Author:
---
For Reviewer:
---
> fix: changed Int64 to string when logging

- app/app_evm.go
---
For Author:
---
For Reviewer:
---
> fix: evm module to use sequencers module instead of staking

- app/app_evm.go
- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---
> merge with main 

- proto/epochs/query.proto
---
For Author:
---
For Reviewer:
---
> fix: fixed epochs proto API path

- x/sequencers/client/cli/gentx.go
---
For Author:
---
For Reviewer:
---
> fix: added keyring-backend flag for gentx_seq

- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---
> chore: Update Dymint version to `v0.5.0-rc3`

- .github/dependabot.yml
---
For Author:
---
For Reviewer:
---
> chore: Add a Dependabot file

- go.mod
- go.sum
- x/dist/keeper/allocation_test.go
- x/dist/module.go
- x/staking/keeper/keeper.go
- x/staking/module.go
---
For Author:
---
For Reviewer:
---
> chore: rebase from main 

- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---
> chore: Upgrade dymint

- x/sequencers/module.go
---
For Author:
---
For Reviewer:
---
> chore: reduced ConsesnsusVersion of sequencers module to 1

- x/dist/doc.go
- x/dist/keeper/allocation.go
- x/dist/keeper/allocation_test.go
---
For Author:
---
For Reviewer:
---
> chore: renaming Agents to Members

- go.mod
- go.sum
- server/commands.go
- server/commands/inspect.go
It produces the following output:
```
>rollappd dymint inspect-state                                                                                                                         
badger 2023/11/14 22:57:22 INFO: All 9 tables opened in 1ms
badger 2023/11/14 22:57:22 INFO: Discard stats nextEmptySlot: 0
badger 2023/11/14 22:57:22 INFO: Set nextTxnTs to 960
badger 2023/11/14 22:57:22 INFO: Deleting empty file: /Users/mtsitrin/.rollapp/data/dymint/000019.vlog
LOADING STATE
{Version:{Consensus:{Block:11 App:0} Software:0.34.29} ChainID:demo-dymension-rollapp InitialHeight:1 LastBlockHeight:228 LastBlockID:A2FB95330C5CED13BF19ACF185A2D34B3A5D9C1DDAFE24755F9B982B414964AD:0:000000000000 LastBlockTime:2023-11-14 20:20:58.9466 +0000 UTC SLStateIndex:0 NextValidators:ValidatorSet{ …
```
> feat: adding_inspect_command

- .github/pull_request_template.md
- .github/workflows/codeql.yml
- .github/workflows/golangci_lint.yml
- .github/workflows/markdown_lint.yml
Close #337
---
For Author:
---
For Reviewer:
---
> Chores: update workflows and template

- go.mod
- go.sum
---
Closes #XXX
For Author:
---
For Reviewer:
---
> build(deps): updated dymint to v1.0.1-alpha

- Makefile
- proto/mint/v1beta1/params.proto
- proto/mint/v1beta1/query.proto
- proto/sequencers/genesis.proto
---
There is a problem with newest proto-gen in #347 so we should have this one in the meantime.
Closes #339
For Author:
---
For Reviewer:
---
> Fix: `make proto-gen` work 

- x/dist/README.md
- x/mint/README.md
- x/mint/types/params.pb.go
- x/sequencers/README.md
- x/sequencers/keeper/dymint.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> docs: add readme to modules

- x/mint/client/cli/query.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> fix(mint): added missing cli query for current inflation

- x/sequencers/types/params.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> fix(sequencer): added HistoricalEntries param validation

- proto/denommetadata/query.proto
- x/denommetadata/client/cli/query.go
- x/denommetadata/keeper/grpc_query.go
- x/denommetadata/types/query.pb.go
- x/denommetadata/types/query.pb.gw.go
---
Closes #370 
For Author:
---
For Reviewer:
---
> feat: add get ibc denom base on denom trace query

- x/denommetadata/keeper/grpc_query.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> fix: fixed ibc voucher denom creation

- x/dist/module.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> chore: setting default values for distribution module

- testutil/app/app.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> chore: 318 merge conflicts

- x/denommetadata/client/cli/test-proposals/create_multiple_denom_metadatas_proposal_test.json
---
Closes #XXX
For Author:
---
For Reviewer:
---
> fix(testing): fixed test proposal template

- go.mod
- go.sum
---
Closes #XXX
For Author:
---
For Reviewer:
---
> build(deps): upgraded dymint to v1.1.0-rc02

- x/epochs/keeper/genesis.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> Chore(epoch): remove epoch count check from validateGenesis

- testutil/app/app.go
- x/dist/keeper/keeper.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> fix(code standards): removes blocked addresses from distr keeper (unused)

- x/hub-genesis/keeper/sequence_numbers.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> fix(hub genesis): check if oustanding seq num exists before decrementing unacked transfers cnt

- server/commands.go
- server/config/config.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> fix(pruning): upstream pruning

- x/gasless/keeper/gasless_test.go
- x/gasless/spec/01_concepts.md
- x/sequencers/keeper/historical_info.go
---
fix some comments
For Author:
---
For Reviewer:
---
> chore: fix some comments

- utils/logger/logger.go
---
Closes #XXX
For Author:
---
For Reviewer:
---
> chore: update logger to milliseconds

- server/commands/p2p_info.go
- x/mint/keeper/mint.go
---
fix some function names
For Author:
---
For Reviewer:
---
> chore: fix some function names

- go.mod
- go.sum
- x/denommetadata/ibc_middleware.go
- x/denommetadata/ibc_middleware_test.go
----
Closes #532 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(ibc): wrap IBC error acknowledgement with an error event

- x/rollappparams/types/params.go
----
Closes #547
I have...
SDK Checklist
----
For Reviewer:
----
> refactor(rollappparams): rollapp param da set default to mock

- x/hub-genesis/client/cli/query.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(genesis_bridge): added genesisInfo query

- x/hub-genesis/keeper/ibc_module.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(hub-genesis): json encoding GenesisBridgeData

- go.mod
- go.sum
- server/commands/rollback.go
----
Closes #581 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollback): add header hash to UpdateStateFromApp

- go.mod
- go.sum
- server/commands/rollback.go
- testutil/app/app.go
- testutil/utils/test_app.go
- x/hub-genesis/keeper/genesis_info.go
----
Closes #569 
I have...
SDK Checklist
----
For Reviewer:
----
> feat: add GenesisChecksum to genesis info

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix: update dymint and cometbft

- server/ante/bypass_ibc_fee_decorator.go
- x/sequencers/keeper/sequencer.go
- x/sequencers/types/errors.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix: clarified whitelisted relayer logs

- x/hub-genesis/types/genesis.go
- x/hub-genesis/types/genesis_test.go
----
Closes #599 
I have...
SDK Checklist
----
For Reviewer:
----
> fix: check for duplicates in genesis info accounts

- x/sequencers/keeper/msg_server.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix bump fumn

- x/gasless/keeper/gasless.go
- x/tokenfactory/types/genesis.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix: genesis validation

- .github/workflows/golangci_lint.yml
- .github/workflows/test.yml
- go.mod
- go.sum
- server/commands.go
- server/commands/liteblockmanager.go
- server/commands/rollback.go
- server/commands/validateinit.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat: validate genesis command

- x/tokenfactory/keeper/createdenom.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(tokenfactory): fixed tokenfactory denom-metadata override

- x/rollappparams/keeper/fees.go
- x/rollappparams/keeper/fees_test.go
- x/rollappparams/keeper/genesis.go
- x/rollappparams/keeper/keeper.go
- x/rollappparams/types/params.go
- x/sequencers/keeper/msg_server_test.go
----
Closes #622 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollappparams): prevent setting drs version through gov prop params change

- server/ante/bypass_ibc_fee_decorator.go
- server/ante/bypass_ibc_fee_decorator_test.go
- server/ante/helpers.go
when checking IBC whitelisting, only check for Client, Connection and Channel related IBC messages
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(ante): skip whitelist check for IBC packet messages

- testutil/utils/test_app.go
- x/hub-genesis/keeper/genesis.go
- x/hub-genesis/keeper/genesis_info.go
- x/hub-genesis/keeper/genesis_info_test.go
- x/hub-genesis/keeper/genesis_transfer.go
- x/mint/keeper/hooks.go
- x/mint/types/params.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(hubgenesis): support non native token rollapps

- go.mod
- go.sum
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> chore(deps): updated dymint to v1.3.0-rc01

- server/proposal/proposal_handler.go
- server/proposal/proposal_handler_test.go
----
Closes #645 
I have...
SDK Checklist
----
For Reviewer:
----
> fix(rollappparams): verify denom for gov proposal gas price change

- x/timeupgrade/types/msgs.go
- x/tokenfactory/keeper/createdenom.go
- x/tokenfactory/keeper/createdenom_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(upstream): upstream fixes to 1.8.0

- go.mod
- go.sum
- server/commands/rollback.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat: bump dymint v1.3.0-rc03 -> v1.3.0-rc03-3d-migration

- x/tokenfactory/bindings/message_plugin.go
- x/tokenfactory/keeper/createdenom.go
- x/tokenfactory/types/denoms.go
- x/tokenfactory/types/denoms_test.go
- x/tokenfactory/types/msgs.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(tokenfactory): validate basic doesn't validate denom

- go.mod
- go.sum
- server/commands.go
- server/commands/liteblockmanager.go
- server/commands/rollback.go
- server/commands/validateinit.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix: cherry pick fixes for 1.8.x

- x/rollappparams/types/params.go
----
Closes #687 
I have...
SDK Checklist
----
For Reviewer:
----
> feat(rollapp param): block da change

- x/rollappparams/types/params.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(da): enable changing da in rollappparams

- server/ante/bypass_ibc_fee_decorator.go
- server/ante/bypass_ibc_fee_decorator_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(ibc): allow whitelist MsgSendTransfer for channel lifecycle

- server/ante/bypass_ibc_fee_decorator.go
- server/ante/bypass_ibc_fee_decorator_test.go
* add send transfer to lifecycle messages
* bump
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> fix(ibc): bump fix for free ibc issue

- server/consensus/handler.go
- utils/logger/logger.go
- utils/sliceutils/utils.go
Optimize code using a more modern writing style.   
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> refactor: use a more modern writing style

- server/ante/bypass_ibc_fee_decorator.go
- server/ante/bypass_ibc_fee_decorator_test.go
----
Closes #XXX
I have...
SDK Checklist
----
For Reviewer:
----
> feat(ante): enhance fee bypass logic for MsgGrant and MsgGrantAllowance
